name: sliding_sheet2
description: A widget that can be dragged and scrolled in a single gesture and snapped to a list of extents.
version: 2.0.0
homepage: https://github.com/ipcjs/sliding_sheet2

environment:
  sdk: '>=2.12.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: